### ISSUE TITLE
Columns of type long256 are not supported

### ISSUE THREAD

**Issue by damiendr** [questdb/py-questdb-client#19]
There doesn't seem to be a way to pass values for `long256` columns at the moment:

```
buffer.row(mytable, columns={col256=<very_large_int>})
```
```python
src/questdb/ingress.pyx in questdb.ingress.Buffer.row()
src/questdb/ingress.pyx in questdb.ingress.Buffer._row()
src/questdb/ingress.pyx in questdb.ingress.Buffer._row()
src/questdb/ingress.pyx in questdb.ingress.Buffer._column()
OverflowError: Python int too large to convert to C long
```

Maybe this could be implemented by checking the value of integer arguments and using the `0x1234i` syntax when appropriate, or via some `Long256` wrapper?

**Comment by amunra** [comment]
Hello!

LONG256 has a few limitations within the database: It can only support equality comparisons (no arithmetic) and it has been mainly added for storing cryptographic hashes.

What's your use case out of curiosity?

**Comment by pswu11** [comment]
Hi @damiendr in case you're not aware, we also have an open community for questdb users: https://slack.questdb.io/

**Comment by amunra** [comment]
Hi @damiendr I'm closing the ticket for now as (to the best of my knowledge) we haven't heard back.
I'm happy to reopen this ticket if there's further demand for the feature.
