### ISSUE TITLE
Reduce the number of necessary parameters when using ILP Auth

### ISSUE THREAD

**Issue by javier** [questdb/py-questdb-client#29]
As per [this issue ](https://github.com/questdb/c-questdb-client/issues/32) on the C/Rust client library, the python implementation shouldn't need to use 4 parameters to establish an ILP authenticated connection, but only 2: kid and d.

Once updated (guess it depends on the base library to be fixed) the examples in the docs should be updated

**Comment by amunra** [comment]
This is not really possible due to the library we use in Rust.
Same would apply if we were to move to openssl (which would bring non-trivial additional complications).
Let's close this.
