### ISSUE TITLE
BUG: When saving a pd.DataFrame with column name "timestamp" it fails

### ISSUE THREAD

**Issue by newskooler** [questdb/py-questdb-client#40]
I am saving a `pd.DataFrame` where one of the columns is named `timestamp`.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/13110986/221150342-2f366bfe-bb12-445a-9668-4ec35c9237c1.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/13110986/221150408-97b72e75-d974-4dbb-9991-3ee28df06d91.png">
I save it in the following way:

```
from questdb.ingress import Sender

with Sender('localhost', 9009) as sender:
    sender.dataframe(df, table_name='my_table')
```

The result in QDB is the following:
![image](https://user-images.githubusercontent.com/13110986/221150858-3fc81eb2-5435-4d2a-b576-3d9fb6aad716.png)
Note how the `timestamp` column is wrongly inputted in QDB for some reason.

**Comment by newskooler** [comment]
Using 
```
with Sender('localhost', 9009) as sender:
    sender.dataframe(df, table_name='my_table', at='timestamp')
```
and making sure that the column is of type `datetime64[ns] or datetime64[ns, tz] column.` solved the problem

**Comment by amunra** [comment]
I'm glad you figured it out :-)
