### ISSUE TITLE
use sqlx::postgres::PgPoolOptions;

### ISSUE THREAD

**Issue by strongguy16** [questdb/py-questdb-client#42]
use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&pool);
    .await?;

    Ok(())
}

_Originally posted by @strongguy16 in https://github.com/questdb/questdb/issues/3204#issuecomment-1519029022_

**Comment by amunra** [comment]
Closing as this is not relevant to the Python client which does not interact with QuestDB via SQL.
Compatibility issues should be reported directly with the core QuestDB project.
