### ISSUE TITLE
Dataframe timestamp column forcibly renamed to 'timestamp'

### ISSUE THREAD

**Issue by fox895** [questdb/py-questdb-client#43]
When importing a dataframe and specifying a timestamp column with `at=...', the column name is discarded and replaced with 'timestamp'.
```python
df = pd.DataFrame({
    'temperature': [20.0, 21.0],
    'humidity': [0.5, 0.6],
    'time': pd.to_datetime(['2021-01-01', '2021-01-02'])})

with Sender('server', 9009) as sender:
    sender.dataframe(df, at='time')
```
![image](https://user-images.githubusercontent.com/2844811/234577650-82f453b9-e9b2-4b1b-a300-8c56d41d02d7.png)

I would expect that the column name is persisted in the final table.

**Comment by amunra** [comment]
This is a limitation of the underlying ILP protocol. Not a client bug. 

Workaround: create the table in advance via SQL via the HTTP or PostgreSQL interface.
