### ISSUE TITLE
Non Timeseries Data

### ISSUE THREAD

**Issue by chandler150** [questdb/py-questdb-client#45]
Is there a way to send a pandas dataframe with no time column?

My use case would be to pull existing time series, run calcs on them, and then reupload kpis back to questdb
This would save me from maintaining a SQL database. 

I see questdb handles it natively by importing a test.csv with their web portal's csv import function.

**Comment by amunra** [comment]
You have a few options here.

The Python client always creates timeseries tables (ie, with a designated timestamp). 

The simplest is to upload the data from the pandas table via the client library and ignore the the fact that you'll end up getting an extra column added.

A cleaner alternative is to create a non-timeseries table via SQL, convert the pandas dataframe to CSV and then upload it via the REST API: https://questdb.io/docs/guides/importing-data-rest/

PS. I'll close this issue, but feel free to reopen it if you have follow-up questions.
