### ISSUE TITLE
Refresh pandas logic with new Pandas 2.0

### ISSUE THREAD

**Issue by amunra** [questdb/py-questdb-client#51]
The current code still works, but creates a few warnings with the latest pandas releases.
This is because it's causing functions that are deprecated.

**Comment by Roh-codeur** [comment]
ran into this just now, if it helps

```
Series.__getitem__ treating keys as positions is deprecated
```

**Comment by Misery42** [comment]
pandas suggest to use:

`df.loc[index, <cloumn_name>]`
`df.loc[index, <cloumn_index>]`
