### ISSUE TITLE
module resolve issue - everything imports as type Any

### ISSUE THREAD

**Issue by Misery42** [questdb/py-questdb-client#58]
![image](https://github.com/questdb/py-questdb-client/assets/42983952/25ed51cd-776f-4d96-b54c-51689b300462)

How to import this module correct?
Is there somthing that need to be fixed?

Using python 3.12 on Windows for development.

Later it runs on a Debian under Docker where typings are not needed.

**Comment by amunra** [comment]
Your import is just fine.

The module is implemented as a native extension in cython.
It's quite possible that this is a tooling limitation where it can't introspect into the module.

Hopefully the documentation is clear enough even if code completion might not fully work in this instance.
