### ISSUE TITLE
Designated timestamp column name is always "timestamp" instead of the given name

### ISSUE THREAD

**Issue by kasparthommen** [questdb/py-questdb-client#68]
1. I run the below code, where I want the column `my_ts` to be the designated timestamp:

```python
df = pd.DataFrame({
    'my_ts': [pd.Timestamp(2024, 3, 21)],
    'my_col': [42],
})

conf = f'http::addr=localhost:9000;'
with Sender.from_conf(conf) as sender:
    sender.dataframe(df, table_name='foo', at='my_ts')
```

2. The resulting table does *not* contain a `my_ts` column but `timestamp` instead. It should be called `my_ts`.

![image](https://github.com/questdb/py-questdb-client/assets/49198627/6cd23411-cb78-4193-8c1e-f3fb3c84780d)

**Comment by amunra** [comment]
This is probably an area that needs better documentation.

**Comment by kasparthommen** [comment]
Fair point, thanks for the workaround/fix!
