### ISSUE TITLE
Sender.from_conf creates log output

### ISSUE THREAD

**Issue by Misery42** [questdb/py-questdb-client#71]
![image](https://github.com/questdb/py-questdb-client/assets/42983952/0618bf6e-773f-4bd0-a394-e149224a2fb6)

Did somebody forget to comment out a "println" ?

**Comment by amunra** [comment]
Issue has been fixed in code, but I didn't get a chance to release 2.0.1 yet. Soon. Sorry for the inconvenience!

**Comment by amunra** [comment]
Fixed in 2.0.1.
