### ISSUE TITLE
Line Protocols UInteger doesn't seam to be supported

### ISSUE THREAD

**Issue by LLukas22** [questdb/py-questdb-client#8]
Can't find a way to insert unsigned integers as described [here](https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#uinteger) into my database.

When i try to provide the column value as an **np.int64** or a **ctypes.c_uint64** i get an unsupported type error.
e.g.
```python
    buffer.row(
        "interval",
        symbols={
            "foo":"bar",
            },
        columns={
            "volume": ctypes.c_uint64(1)
        },
        at=TimestampNanos(12345)
    )
```
throws

```
Unsupported type: <class 'ctypes.c_ulonglong'>. Must be one of: bool, int, float, str, TimestampMicros, datetime.datetime
```

When i provide the value as a python integer its always commited as a [line protocol integer](https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#integer) which leads to problems when dealing with huge numbers.

Is there a workaround for this behaviour or is this the intended behaviour?

**Comment by amunra** [comment]
The type is indeed not supported (by design).
The way to do this is to cast it to the appropriate Python type: In this case `int`.

From a `ctypes.c_uint64(1)`, call `.value`:

```python
>>> import ctypes
>>> c_num = ctypes.c_uint64(42)
>>> type(c_num)
<class 'ctypes.c_ulong'>
>>> num = c_num.value
>>> type(num)
<class 'int'>
```

From a `np.int64`, pass it as arg to the `int(..)` builtin:
```
>>> import numpy as np
>>> np_num = np.int64(42)
>>> type(np_num)
<class 'numpy.int64'>
>>> num = int(np_num)
>>> type(num)
<class 'int'>
```
