### ISSUE TITLE
Pandas concatenation leads to timestamp error when sending data

### ISSUE THREAD

**Issue by shassen14** [questdb/py-questdb-client#97]
I was following the [tutorial here](https://questdb.io/docs/third-party-tools/pandas/) regarding sending data over to a QuestDB table. Sending a dataframe to a table in this example works perfectly fine from my testing.

I try to recreate the same table using `pd.concat()` function and then sending the dataframe over the same way. Then I encounter this error: 
```
Got error: Bad column 'timestamp': Unsupported object column containing an object of type pandas._libs.tslibs.timestamps.Timestamp.
```

Here is the sample code:
``` python
columns = ["pair", "traded_price", "qty", "limit_price", "timestamp"]
host = "localhost"
port = 9009

test_df = pd.DataFrame(columns=columns)
test_df = pd.concat([test_df, 
		     pd.Series(["USDGBP", 
			        0.83, 
				100, 
				0.84,
				pd.Timestamp('2022-08-06 07:35:23.189062', tz='UTC')],  
				index=columns)
		     .to_frame().T], 
		     ignore_index=True)
test_df = pd.concat([test_df, 
		     pd.Series(["EURJPY", 
		                142.62, 
		                400, 
		                None, 
		                pd.Timestamp('2022-08-06 07:35:23.189062', tz='UTC')],  
		     index=columns)
		     .to_frame().T], 
		     ignore_index=True)

try:
    with Sender(Protocol.Tcp, host, port) as sender:
        sender.dataframe(
            test_df,
	    table_name='test2',  # Table name to insert into.
	    symbols=['pair'],  # Columns to be inserted as SYMBOL types.
	    at='timestamp')  # Column containing the designated timestamps.

except IngressError as e:
	sys.stderr.write(f'Got error: {e}\n')
```

Looking at both dataframes from the tutorial and the one concatenated, they seem to be identical outputting this result each time

```
	pair	traded_price	qty	limit_price	timestamp
0	USDGBP	0.83	        100	   0.84	        2022-08-06 07:35:23.189062+00:00
1	EURJPY	142.62	        400	   None	        2022-08-06 07:35:23.189062+00:00
```

To "solve" this issue, I added this line to edit the timestamp column right before sending the dataframe over.
```
test_df['timestamp'] = pd.to_datetime(test_df.timestamp)
```

Could we send a concatenated pandas dataframe over without adding this line? Am I doing something wrong? Please feel free to teach me. I'm still learning. Thanks!

**Comment by amunra** [comment]
# Schema type issues

The core of the issue here is that your pandas dataframe is effectively untyped.

```
# ... your existing code
test_df.info(verbose=True)
```

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   pair          2 non-null      object
 1   traded_price  2 non-null      object
 2   qty           2 non-null      object
 3   limit_price   1 non-null      object
 4   timestamp     2 non-null      object
dtypes: object(5)
memory usage: 208.0+ bytes
```

Every column is an `object` column.

Our `questdb` library requires typed columns, since it can then perform serialization in native code, instead of doing it at the Python layer. Python-level serialization (i.e. object columns) is only really supported for strings and that's about it.
This is because it's simply too slow to be practically useful (about two orders of magnitude slower, see https://github.com/questdb/py-tsbs-benchmark/blob/main/README.md)

Instead you want to construct your dataframe in a way that allows you to maintain a typed schema:
```
columns = ["pair", "traded_price", "qty", "limit_price", "timestamp"]
rows = [
    ["USDGBP", 
        0.83, 
        100, 
        0.84,
        '2022-08-06 07:35:23.189062'],
    ["EURJPY", 
        142.62, 
        400, 
        None, 
        '2022-08-06 07:35:23.189062']
]

# transpose into dict of names to column values
data = {
    col: values
    for col, values
    in zip(columns, map(list, zip(*rows)))}

# set the types on the first and last columns explicitly
data['pair'] = pd.Series(data['pair'], dtype='string[pyarrow]')
data['timestamp'] = pd.Series(data['timestamp'], dtype='datetime64[ns, UTC]')

test_df = pd.DataFrame(data)

test_df.info(verbose=True)
```

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype              
---  ------        --------------  -----              
 0   pair          2 non-null      string             
 1   traded_price  2 non-null      float64            
 2   qty           2 non-null      int64              
 3   limit_price   1 non-null      float64            
 4   timestamp     2 non-null      datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(2), int64(1), string(1)
memory usage: 220.0 bytes
```

In general, if you need to append a number of rows dynamically, do this _before_ constructing the dataframe. It will also execute significantly faster.

# Using a connection string

In your example, I also recommend:
* Using the newer HTTP, not TCP
* Using a configuration string, i.e. `Sender.from_conf(...)` or `Sender.from_env(...)`.
  See: https://py-questdb-client.readthedocs.io/en/latest/examples.html#data-frames

**Comment by amunra** [comment]
Side note, instead of strings you might want to use a categorical type if in Pandas if you have the same keys over and over.

```
data['pair'] = pd.Categorical(data['pair'])
```

**Comment by amunra** [comment]
I'll close this issue now, but feel free to re-open if you have more issues.

**Comment by shassen14** [comment]
Ahh I see I see. That makes total sense. Thank you for taking the time to explain that and recommendations! This has been really helpful!
